version: '3'

services:
  db:
    image: mysql:${MYSQL_VERSION-5.7}
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - 5432:3306
    networks:
      - web_app
  php:
    build:
      context: ./.docker/php
    volumes:
      - ./:/var/www/html
    networks:
      - web_app
    depends_on:
      - db
  nginx:
    build:
      context: ./.docker/nginx
    volumes:
      - ./:/var/www/html
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
    networks:
      - web_app
    depends_on:
      - php
      - db

volumes:
  web_data:
  db_data:

networks:
  web_app: